# Anti-spam config. Edit and restart the bot.
admin_ids: [5159778359, 1460947124, 1985599703, 1413315052,6833495660, 268242809, 5355822214, 1096480418, 1481450018, 5084589299, 1434456559, 1465174595, 650142484, 814874783, 6421544549, 838727675, 841727967, 127171717, 92246968, 550812760, 283194117, 745014028, 1741048309]        # e.g. [123456789, 987654321]
allowed_tme:         # t.me links allowed (your own channel/chat).
  - "t.me/your_channel"
  - "t.me/your_chat"
  - "t.me/https://t.me/sportcarusdt"
  - "https://t.me/grotesqueriebtc"
allowed_domains:     # trusted non-Telegram domains allowed
  - "your-site.com"
  - "https://www.mexc.com/ru-RU/futures-activity/trading-competition?id=MzAwLXBlcnNvbmFsR2FtZQ%3D%3D&utm_source=kol&utm_medium=kol&inviteCode=1NUMA"
  - "https://www.mexc.com/campaigns/invite-sep2-user?inviteCode=1NUMA"
  - "https://www.okx.com/join/61133973"
  - "https://partner.bybit.com/b/50364"
  - "https://www.toobit.com/t/knPs69"
  - "https://www.instagram.com/konstantinnistor"
  - "https://t.me/boost/grotesqueriebtc"
  - "https://ozon.ru/t/h1EAhN0"
  - "https://www.mexc.com/ru-RU/register?inviteCode=mexc-1NUMA"
keywords_block:
  - "–∑–∞—Ä–∞–±–æ—Ç–æ–∫ –æ–Ω–ª–∞–π–Ω"
  - "–ª—ë–≥–∫–∏–π –∑–∞—Ä–∞–±–æ—Ç–æ–∫"
  - "–ª–µ–≥–∫–∏–π –∑–∞—Ä–∞–±–æ—Ç–æ–∫"
  - "–ø–∞—Å—Å–∏–≤–Ω—ã–π –¥–æ—Ö–æ–¥"
  - "–±–∏–Ω–∞—Ä–Ω—ã–µ –æ–ø—Ü–∏–æ–Ω—ã"
  - "—Å–∏–≥–Ω–∞–ª—ã"
  - "–ø—Ä–∏–≤–∞—Ç–Ω—ã–π –∫–∞–Ω–∞–ª"
  - "–≤–∞–∫–∞–Ω—Å–∏—è"
  - "—É–¥–∞–ª—ë–Ω–Ω–∞—è —Ä–∞–±–æ—Ç–∞"
  - "—É–¥–∞–ª–µ–Ω–Ω–∞—è —Ä–∞–±–æ—Ç–∞"
  - "–±–µ—Å–ø–ª–∞—Ç–Ω–∞—è –∫–Ω–∏–≥–∞"
  - "pdf –∫–Ω–∏–≥–∞"
  - "–æ–±—É—á–µ–Ω–∏–µ —Å –Ω—É–ª—è"
  - "100% –≥–∞—Ä–∞–Ω—Ç–∏—è"
  - "–ø—Ä–æ–≤–µ—Ä–µ–Ω–Ω–∞—è —Å—Ö–µ–º–∞"
  - "–¥–æ–≤–µ—Ä–∏—Ç–µ–ª—å–Ω–æ–µ —É–ø—Ä–∞–≤–ª–µ–Ω–∏–µ"
  - "–ø—Ä–∏–≥–ª–∞—à–∞—é –≤ —á–∞—Ç"
  - "–ø—Ä–∏–≥–ª–∞—à–∞—é –≤ –∫–∞–Ω–∞–ª"
  - "—Å–µ—Ç–µ–≤–æ–π –º–∞—Ä–∫–µ—Ç–∏–Ω–≥"
  - "–ø–∏—Ä–∞–º–∏–¥–∞"
  - "–∫—ç—à–±–µ–∫ 50%"
  - "airdrop –∑–∞ —Ä–µ—Ñ"
  - "—Ä–µ—Ñ–µ—Ä–∞–ª—å–Ω–∞—è —Å—Å—ã–ª–∫–∞"
  - "join my channel"
  - "work from home"
  - "easy money"
  - "—Ä–∞–±–æ—Ç–∞ –∏–∑ –¥–æ–º–∞"
  - "–æ–Ω–ª–∞–π–Ω-–∑–∞—Ä–∞–±–æ—Ç–∫–∞"
  - "—É–¥–∞–ª—ë–Ω–∫–∞ —Å –¥–æ—Ö–æ–¥–æ–º"
  - "–±–µ–∑ —Å—Ç–∞–≤–æ–∫, –±–µ–∑ –∑–∞–∫–ª–∞–¥–æ–∫"
  - "–±—ã—Å—Ç—Ä—ã–º —Å—Ç–∞—Ä—Ç–æ–º"
  - "–ª–µ–≥–∞–ª—å–Ω—ã–π —Å–ø–æ—Å–æ–± –∑–∞—Ä–∞–±–æ—Ç–∫–∞"
  - "–º–æ–≥—É –æ—Ç–ø—Ä–∞–≤–∏—Ç—å —Ç–µ–º"
  - "–∑–∞–∏–Ω—Ç–µ—Ä–∏—Å–æ–≤–∞–ª–æ –º–æ–≥—É —Å–∫–∏–Ω—É—Ç—å"
  - "–ø—Ä–æ—Ö–æ–¥–∏—Ç –æ–±—É—á–µ–Ω–∏–µ –¥–ª—è –Ω–æ–≤–∏—á–∫–æ–≤"
  - "—É–¥a–ª–µ–Ω–Ω–æ –∏–∑ –¥–æ–º–∞"
  - "–±–µ–ª–æ–µ –Ω–∞–ø—Ä–∞–≤–ª–µ–Ω–∏–µ"
  - "–°–†–û–ß–ù–û –Ω—É–∂–Ω—ã 2 —É–¥–∞–ª–µ–Ω—â–∏–∫–∞"
  - "–ª–µ–≥–∞–ª—å–Ω–æ –∏ –±–µ–∑–æ–ø–∞—Å–Ω–æ"
  - "–î–µ—Ç–∞–ª–∏ –≤ –õ–°"
  - "–ø–∏—à–∏—Ç–µ ¬´+¬ª"
  - "–†–∞–±–æ—Ç–∞ –Ω–∞ –¥–æ–º—É —Å –∫–æ–º–ø—å—é—Ç–µ—Ä–∞"
  - "–î–∏—Å—Ç–∞–Ω—Ü–∏–æ–Ω–Ω–∞—è –¥–µ—è—Ç–µ–ª—å–Ω–æ—Å—Ç—å"
  - "–¥–æ–ª–ª–∞—Ä–æ–≤ –≤ –Ω–µ–¥–µ–ª—é"
  - "–ò—â–µ–º —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤ –¥–ª—è –∞–Ω–∞–ª–∏—Ç–∏—á–µ—Å–∫–æ–π —Ä–∞–±–æ—Ç—ã"
  - "–ò—Å–∫–ª—é—á–∏—Ç–µ–ª—å–Ω–æ 18+"
  - "–°—Ç–∞–±–∏–ª—å–Ω–æ –∏ –ª–µ–≥–∞–ª—å–Ω–æ"
  - "–°–†–û–ß–ù–û –í –ü–£–ë–õ–ò–ß–ù–û–ú –î–û–°–¢–£–ü–ï"
  - "–†–∞—Å—Å—ã–ª–∫–∞ –≤–∞—à–µ–≥–æ –æ–±—ä—è–≤–ª–µ–Ω–∏—è"
  - "–°—Ç–∞–±–∏–ª—å–Ω–∞—è –æ–ø–ª–∞—Ç–∞"
  - "–ó–∞—Ä–∞–±–æ—Ç–æ–∫ –æ—Ç"
  - "–†–∞–±–æ—Ç–∞ –¥–ª—è –≤—Å–µ—Ö"
  - "–†–µ–±—è—Ç —è —Ç—É—Ç –ø—Ä–æ—á–∏—Ç–∞–ª –æ–¥–Ω—É –∫–Ω–∏–≥—É"
  - "–ò—â—É –ª—é–¥–µ–π –¥–ª—è –≤–æ—Ä–∫–∞"
  - "–≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –ø–æ–¥–Ω—è—Ç—å –Ω–µ–º–Ω–æ–≥–æ –±–∞–±–ª–∞"
  - "–£–î–ê–õ–Å–ù–ù–ê–Ø –ó–ê–ù–Ø–¢–û–°–¢–¨"
  - "–ö–æ–º—É –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ –ø–∏—à–∏—Ç–µ"
  - "–ù–£–ñ–ù–´ 3-4 —á–µ–ª–æ–≤–µ–∫–∞ –í –ü–†–û–ï–ö–¢"
  - "–≤—Å—ë –ª–µ–≥–∞–ª—å–Ω–æ –∏ –ø—Ä–æ–∑—Ä–∞—á–Ω–æ"
  - "–ü–∏—à–∏—Ç–µ –≤ –ª–∏—á–Ω—ã–µ —Å–æ–æ–±—â–µ–Ω–∏—è"
  - "–≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –ø–æ–ª—É—á–∞—Ç—å –¥–æ—Ö–æ–¥"
  - "–î–∏—Å—Ç–∞–Ω—Ü–∏–æ–Ω–Ω–∞—è –¥–µ—è—Ç–µ–ª—å–Ω–æ—Å—Ç—å"
  - "–¢–∞–º –º–æ–∏ –∏–Ω—Ç–µ—Ä–µ—Å—ã–µ —Ñ–æ—Ç–æ"
  - "–¢–∞–º –º–æ–∏ –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã–µ —Ñ–æ—Ç–æ"
  - "–õ–µ–≥–∞–ª—å–Ω–∞—è —Ç–µ–º–∫–∞"
  - "–Ω–µ —á–µ—Ä–Ω—É—Ö–∞"
  - "–í—Å–µ –æ–±—ä—è—Å–Ω—é —Ä–∞—Å—Å–∫–∞–∂—É"
  - "–ü–ª–∞—á—É –¥–æ"
  - "–ö–æ–º—É –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ , –ø–∏—à–∏—Ç–µ"
  - "–≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å —Å—Ç–∞–±–∏–ª—å–Ω–æ–≥–æ  –¥–æ—Ö–æ–¥–∞"
  - "–î–æ—Ö–æ–¥ ‚Äî –¥–æ"
  - "–ø—Ä–µ–¥–æ—Å—Ç–∞–≤–ª—è—é—Ç—Å—è –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏"
  - "—É–∑–Ω–∞—Ç—å –ø–æ–¥—Ä–æ–±–Ω–æ—Å—Ç–∏"
  - "–ò—â—É 2-3 —É–¥–∞–ª–µ–Ω—â–∏–∫–∞"
  - "—Ä–∞–±–æ—Ç–∞ —É–¥–∞–ª—ë–Ω–Ω–æ"
  - "–ë–µ—Å–ø–ª–∞—Ç–Ω–æ–µ –æ–±—É—á–µ–Ω–∏–µ"
  - "–ó–∞ –ø–æ–¥—Ä–æ–±–Ω–æ—Å—Ç—è–º–∏ –≤ –õ–°"
  - "–°–†–û–ß–ù–û –Ω—É–∂–Ω—ã"
  - "–û–Ω–ª–∞–π–Ω-–∑–∞–Ω—è—Ç–æ—Å—Ç—å"
  - "–û—Ç–∫—Ä—ã—Ç –Ω–∞–±–æ—Ä"
  - "–ü–æ—à–∞–≥–æ–≤–æ–µ –æ–±—É—á–µ–Ω–∏–µ"
  - "–ª–∏—á–Ω–æ–µ —Å–æ–ø—Ä–æ–≤–æ–∂–¥–µ–Ω–∏–µ"
  - "–ù–∞–ø–∏—à–∏ ¬´+¬ª"
  - "–ï—Å—Ç—å –≤–æ—Ä–∫"
  - "–û–ø–ª–∞—Ç–∞ –¥–æ"
  - "–ü–∏—à–∏—Ç–µ, –µ—Å–ª–∏ –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ"
  - "–∑–∞ 3-4 —á–∞—Å–∞!"
  - "–í—Å—ë —Å —Ç–µ–ª–µ—Ñ–æ–Ω–∞"
  - "—Å—Å—ã–ª–∫–∞ –≤ –ø—Ä–æ—Ñ–∏–ª–µ"
  - "–í—ã–Ω—É–∂–¥–µ–Ω –ø–æ–ø—Ä–æ—Å–∏—Ç—å –ø–æ–º–æ—â–∏"
  - "–û–ø—ã—Ç –Ω–µ –Ω—É–∂–µ–Ω"
  - "–ù–∞–ø–∏—à–∏—Ç–µ –≤ –õ–°"
  - "–¥–ª—è –ø–æ–¥—Ä–æ–±–Ω–æ—Å—Ç–µ–π"
  - "–†–∞–±–æ—Ç–∞ —É–¥–∞–ª—ë–Ω–Ω–∞—è"
  - "–ü–∏—à–∏, –µ—Å–ª–∏ –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ "
  - "–í–æ–∑–º–æ–∂–Ω—ã–π –¥–æ—Ö–æ–¥ –æ—Ç"
  - "–Ω–∞–ø–∏—à–∏ –º–Ω–µ ¬´+¬ª"
  - "–¢–û–ü1 –ö–ê–ó"
  - "–°–ê–ú–´–ï –í–´–°–û–ö–ò–ï RTP"
  - "–∏—â—É –¥—Ä–æ–ø–æ–≤–æ–¥–æ–≤"
  - "–ü–æ–∫—É–ø–∞—é –∫–∞—Ä—Ç—ã"
  - "–±–µ–ª–æ–π —Ç–µ–º—ã"
  - "—Ç–µ–º –ø–æ –∑–∞—Ä–∞–±–æ—Ç–∫—É"
  - "–ü–∏—à–∏—Ç–µ –≤ –õ–°"
  - "–î–∞–º –≤–æ—Ä–∫"
  - "–ø–æ–¥—Ä–∞–±–æ—Ç–∫–∞"
  - "–ú—ã –≤—Å–µ –æ–±–µ—Å–Ω–∏–º"
  - "–í—Å–µ –±–µ–∑–æ–ø–∞—Å–Ω–æ"
  - "–∑–∞ —á–µ–ª–æ–≤–µ–∫–∞ –ø–æ–ª—É—á–∞–µ—Ç–µ"
  - "–∑–∞–¥–∞—á–∞ —Ä–µ–∫–ª–∞–º–∏—Ä–æ–≤–∞—Ç—å"
  - "–ù—É–∂–Ω—ã –∞–¥–µ–∫–≤–∞—Ç–Ω—ã–π"
  - "–î–∞–π—Ç–µ –∑–Ω–∞—Ç—å"
  - "–∫—Ç–æ –∑–∞–∏–Ω—Ç–µ—Ä–µ—Å–æ–≤–∞–Ω"
  - "—É–¥–∞–ª—ë–Ω–Ω–æ–π —Ä–∞–±–æ—Ç–µ"
  - "–ø–∏—à–∏—Ç–µ —Å—é–¥–∞"
  - "–ö—Ç–æ –≥–æ—Ç–æ–≤ –ø–æ–ø—Ä–æ–±–æ–≤–∞—Ç—å"
  - "–ò—â–µ–º –ª—é–¥–µ–π"
  - "–∞–Ω–∞–ª–∏—Ç–∏—á–µ—Å–∫–æ–π —Ä–∞–±–æ—Ç—ã"
  - "–∑a —Äe–≥–∏c—Çpa—Ü–∏—é"
  - "3a–Ω–∏–ºae—Ç 10 –º–∏–Ωy—Ç"
  - "—Ç–æ–ª—å–∫–æ 18+"
  - "–ñ–¥—É –≤ –ª—Å"
  - "–ë–ê–õ–ê–ùC –ü–£–®K–ò–ù–°–ö–û–ô"
  - "–ï–°–¢–¨ –ì–ê–†–ê–ù–¢–ò–Ø"
  - "–ø—Ä–æ—Å—Ç—ã–µ –¥–µ–π—Å—Ç–≤–∏—è"
  - "–î–∞–º 15Œ∫"
  - "–ú–£–¢–ò–¢–¨ –¢–ï–ú–ö–ò"
  - "–ë–ï–ó –í–õ–û–ñ–ï–ù–ò–ô"
  - "–¢–ï–ú–ö–ò –°–ï–†–´–ï"
  - "–ü–û –í–°–ï–ú –í–û–ü–†–û–°–ê–ú"
  - "–ï—Å—Ç—å —Ç–µ–º–∫–∞"
  - "–ü–∏—à–∏—Ç–µ –≤ –õ–°!"
  - "–ü–∏—à–∏—Ç–µ –≤ –õ–°"
  - "–ø–æ–¥–¥–µ—Ä–∂–∫—É –ø–æ—á—Ç–∞ –±–∞–Ω–∫–∞"
  - "–°–ö–£–ü–ê–Æ –ë–ê–õ–ê–ù–°"
  - "–ü–û–ú–ï–¢–ö–ê –û–¢ –°–ö–ê–ú–ê"
  - "–ù–∞–¥–æ –º–Ω–æ–≥–æ. –ò–¥–µ—Ç –≤—ã–∫—É–ø"
  - "–±—ã—Å—Ç—Ä–æ –ø–æ–¥–∑–∞—Ä–∞–±–æ—Ç–∞—Ç—å"
  - "–±—ã—Å—Ç—Ä–æ –ø–æ–¥–∑–∞—Ä–∞–±–æ—Ç–∞—Ç—å?"
  - "–∑–∞ –ø–∞—Ä—É —á–∞—Å–æ–≤"
  - "–ø–æ–¥—Ä–æ–±–Ω–æ—Å—Ç—è–º–∏ –ø–∏—à–∏ —Å—é–¥–∞"
  - "–ü—Ä–æ–µ–∑–¥ –æ–ø–ª–∞—á–∏–≤–∞–µ–º"
  - "—É–¥–∞–ª—ë–Ω–Ω—ã–π –ø—Ä–æ–µ–∫—Ç"
  - "–≤—ã–ø–æ–ª–Ω–µ–Ω–∏–µ –ø—Ä–æ—Å—Ç—ã—Ö —à–∞–≥–æ–≤"
  - "¬´+¬ª"
  - "–∞–∫—Ç—É–∞–ª—å–Ω—ã–µ –º–µ—Ç–æ–¥—ã"
  - "–∞–±—Å–æ–ª—é—Ç–Ω–æ –±–µ—Å–ø–ª–∞—Ç–Ω–æ"
  - "Nexus"
  - "–≤—ã—Å–æ–∫–∏–µ –∫–æ—ç—Ñ—Ñ–∏—Ü–∏–µ–Ω—Ç—ã"
  - "–ø–æ–±–µ–∂–¥–∞—Ç—å –∏ –∑–∞—Ä–∞–±–∞—Ç—ã–≤–∞—Ç—å"
  - "–ù—É–∂–Ω—ã –ª—é–¥–∏"
  - "—É–¥–∞–ª—ë–Ω–Ω–æ–≥–æ —Ñ–æ—Ä–º–∞—Ç–∞"
  - "–Ω—É–∂–µ–Ω —Ç–æ–ª—å–∫–æ —Ç–µ–ª–µ—Ñ–æ–Ω"
  - "–¥–æ—Ö–æ–¥ –Ω–∞—á–∏–Ω–∞–µ—Ç—Å—è –æ—Ç"
  - "–í—Å—ë –æ–±—ä—è—Å–Ω—è–µ—Ç—Å—è"
  - "–Ω–∞—á–∞—Ç—å –∑–∞—Ä–∞–±–∞—Ç—ã–≤–∞—Ç—å"
  - "–û–ø–ª–∞—Ç–∞ –æ—Ç"
  - "–†–∞–±–æ—Ç–∞—é –º–Ω–æ–≥–æ –ª–µ—Ç"
  - "üí∞Prise"
  - "–ΩŒø–≤—É—é —Ç–µ–º–∫—É"
  - "–ø–æ–¥–Ω–∏–º–∞—Ç—å –æ—Ç"
  - "–ù–∞–ø–∏—à–º—Ç–µ –≤ –õ–°"
  - "–≤—Å—ë œÅ–∞—Å—ÅŒ∫–∞–∂—É"
  - "–ï—Å—Ç—å —Ä–∞–∑–æ–≤–æ–µ –∑–∞–¥–∞–Ω–∏–µ"
  - "–ø–∏—à–∏—Ç–µ –≤ –ª–∏—á–∫—É"
  - "–ü–ª–∞—á—É –ø–æ"
  - "–í –õ–°"
  - "–Ω–µ–±–æ–ª—å—à–æ–µ –∑–∞–¥–∞–Ω–∏–µ"
  - "–î–∞–º –Ω–∞ —Ä—É–∫–∏"
  - "–Ω–æ–≤–∞—è —Ç–µ–º–∞"
  - "–ü—Ä–æ—Ñ–∏—Ç –æ—Ç"
  - "–ü–†–ê–ô–° –õ–ò–°–¢"
  - "–ü–ò–°–ê–¢–¨ –í –õ–°"
  - "–¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–∞—è –∑–∞–Ω—è—Ç–æ—Å—Ç—å"
  - "–≤ —Ä—É–∫–∏"
keywords_allow:      # allow-listed crypto words to reduce false positives
  - "–±–∏—Ç–∫–æ–∏–Ω"
  - "bitcoin"
  - "—ç—Ñ–∏—Ä"
  - "ethereum"
  - "usdt"
  - "binance"
  - "okx"
  - "bybit"
  - "airdrops"
anti_raid_minutes: 1
